services:
  web:
    build:
      context: .
    environment:
      APPLICATION_ENV: 'testing'
      LOG_LEVEL: 'debug'
    volumes:
      - ./vendor:/var/ambientcast/www/vendor
      - .:/var/ambientcast/www
