services:
  web:
    build:
      context: .
      # Control wether Liquidsoap should be built from source via OPAM or download the
      # pre-built .deb file from the Liquidsoap GitHub Releases on ARM based machines
      # args:
      #   ARM_FULL_BUILD: true
    ports:
      - "127.0.0.1:3306:3306"
      - "127.0.0.1:6379:6379"
    volumes:
      - $PWD/util/local_ssl/default.crt:/var/ambientcast/acme/ssl.crt:ro
      - $PWD/util/local_ssl/default.key:/var/ambientcast/acme/ssl.key:ro
      - $PWD/vendor:/var/ambientcast/www/vendor
      - $PWD:/var/ambientcast/www
    extra_hosts:
      - "host.docker.internal:host-gateway"
