services:
  frontend:
    container_name: ambientcast_frontend
    build:
      context: ./frontend
    user: "${AMBIENTCAST_PUID:-1000}:${AMBIENTCAST_PGID:-1000}"
    volumes:
      - $PWD/frontend:/data/frontend
      - $PWD/resources/locale:/data/resources/locale
      - $PWD/web/static:/data/web/static
      - frontend_node_modules:/data/frontend/node_modules

volumes:
  frontend_node_modules: { }
