---
- name: Ensure update script continues to be executable
  file:
    path: "{{ ambientcast_setup_update_script }}"
    state: touch
    mode: "a+x"
  loop:
    - "{{ www_base }}/update.sh"
    - "{{ www_base }}/bin/console"
  loop_control:
    loop_var: ambientcast_setup_update_script

- name: Run AmbientCast Setup (Install Mode)
  become: true
  become_user: ambientcast
  shell: >-
    php {{ www_base }}/bin/console ambientcast:setup
  when: not update_mode|bool

- name: Migrate Legacy Configuration (Update Mode)
  become: true
  become_user: ambientcast
  shell: >-
    php {{ www_base }}/bin/console ambientcast:config:migrate
  when: update_mode|bool

- name: Run AmbientCast Setup (Update Mode)
  become: true
  become_user: ambientcast
  shell: php {{ www_base }}/bin/console ambientcast:setup --update
  when: update_mode|bool
