---
- hosts: all
  become: true

  vars:
    util_base: "{{ playbook_dir | dirname }}"
    www_base: "{{ util_base | dirname }}"
    app_base: "{{ www_base | dirname }}"
    tmp_base: "{{ app_base }}/www_tmp"
    app_env: "production"
    update_mode: false
    dev_ambientcast_user_password: "ambientcast"
    dev_mysql_user_password: "ambientcast"

  environment:
    DEBIAN_FRONTEND: noninteractive

  roles:
    - init
    - ambientcast-user
    - ambientcast-config
    - ambientcast-radio
    - supervisord
    - nginx
    - php
    - redis
    - beanstalkd
    - sftpgo
    - mariadb
    - ufw
    - dbip
    - composer
    - services
    - ambientcast-db-install
    - ambientcast-build
    - ambientcast-setup
    - ambientcast-cron
