---
- name: Generate AmbientCast Password
  command: >-
    pwgen 8 -sn 1
  register: prod_ambientcast_user_password

- name: Create Groups
  group:
    name: "{{ ambientcast_user_sys_group }}"
    state: present
  loop:
    - www-data
    - admin
  loop_control:
    loop_var: ambientcast_user_sys_group

- name: Create AmbientCast User
  user:
    name: ambientcast
    home: "{{ app_base }}"
    comment: "AmbientCast"
    shell: /bin/bash
    groups: 'sudo,admin,www-data'
    password: "{{ prod_ambientcast_user_password.stdout|password_hash('sha512') }}"
  notify: send user notification

- name: Modify www-data User
  user:
    name: www-data
    groups: "ambientcast"
    append: true
