#!/usr/bin/env bash

MYSQL_USER="${MYSQL_USER:-ambientcast}"
MYSQL_PASSWORD="${MYSQL_PASSWORD:-ambient4c457}"
MYSQL_DATABASE="${MYSQL_DATABASE:-ambientcast}"

exec gosu mysql mysql -u${MYSQL_USER} -p${MYSQL_PASSWORD} -D ${MYSQL_DATABASE}